name: agent_distributor_app
description: Приложение агента с заказами, точками, профилем и авторизацией.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI и Состояние ---
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  flutter_hooks: ^0.20.5

  # --- Сеть и API ---
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0 # если хочешь безопасно хранить токены

  # --- Модели и кодогенерация ---
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # --- Утилиты ---
  intl: ^0.18.1
  uuid: ^4.0.0 # если нужно генерировать ID для заказов/точек

  # --- Навигация (по желанию) ---
  go_router: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf
